translate(participation-details): translate to pt-br
womenwhogocwb/hacktoberfest2020 pull request #3
Opened 2020-10-01 00:49 UTC by danditeoa

2020-10-01 12:08 UTC, c-caaah commented
@danditeoa eu seguria só o padrão de colocar as letras em ingl~es em itálico.
Tirando isso tá ótimo

2020-10-01 12:11 UTC, amandabrbz requested changes
Consegue fazer essas adaptações para nós Dandiii?! :D

2020-10-01 12:11 UTC, amandabrbz commented on detalhes-pt-br.md
> +- As solicitações de pull request podem ser feitas em qualquer repositório ou projeto hospedado no GitHub. Contanto que o projeto esteja público e hospedado no GitHub, suas solicitações de pull reque
Eu deixaria a público e hospedado no Github em negrito.

2020-10-01 12:11 UTC, amandabrbz commented on detalhes-pt-br.md
> +- Você pode se inscrever a qualquer momento entre 1º de outubro e 31 de outubro. Apenas certifique-se de se inscrever no site oficial do Hacktoberfest para que suas solicitações de pull request sejam
Tem como deixar as palavras em inglês em itálico? só para a gente seguir padrão?

2020-10-01 12:11 UTC, c-caaah commented on detalhes-pt-br.md
> +- Você pode se inscrever a qualquer momento entre 1º de outubro e 31 de outubro. Apenas certifique-se de se inscrever no site oficial do Hacktoberfest para que suas solicitações de pull request sejam
@danditeoa eu deixaria no padrão do restante da tradução e colocaria as palavras em inglês em itálico. Fora isso pra mim o texto tá ótimo

2020-10-01 12:17 UTC, c-caaah requested changes

2020-10-01 12:17 UTC, c-caaah commented on detalhes-pt-br.md
> +- As solicitações de pull request podem ser feitas em qualquer repositório ou projeto hospedado no GitHub. Contanto que o projeto esteja público e hospedado no GitHub, suas solicitações de pull reque
@danditeoa eu deixaria no padrão do restante da tradução e colocaria as palavras em inglês em itálico. Fora isso pra mim o texto tá ótimo

2020-10-01 12:44 UTC, erikacarvalho commented on detalhes-pt-br.md
> +- Você pode se inscrever a qualquer momento entre 1º de outubro e 31 de outubro. Apenas certifique-se de se inscrever no site oficial do Hacktoberfest para que suas solicitações de pull request sejam
massa dandi! aproveita que você vai mexer e bota o link pro site da hacktoberfest (https://hacktoberfest.digitalocean.com/) ali em "site oficial da hacktoberfest", que acha?

2020-10-03 01:24 UTC, amandabrbz approved these changes

2020-10-03 01:25 UTC, c-caaah approved these changes

2020-10-03 01:25 UTC, merged